### ISSUE TITLE
Player name page ... update

### ISSUE THREAD

**Issue by withrvr** [Connecting-Dots-Forever/Connect-4#7]
![Image](https://user-images.githubusercontent.com/69628500/241793476-5960a0c4-7168-4380-a33e-d4c1fd969ca2.png)

- create list of this
- and pick random from this
- so more choice 
-
- ie not only Adventurer .... then other will also be included

**Comment by withrvr** [comment]
- ONE ready button ?????

**Comment by withrvr** [comment]
### if both color same
- then don't go to next page

**Comment by withrvr** [comment]
# color picker ?


- in that hash tag will be included automatically

![Image](https://github.com/Connecting-Dots-Forever/Connect-4/assets/69628500/d2f9bbbe-220b-4247-9a11-d9a0c055f87e)

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_color



![Image](https://github.com/Connecting-Dots-Forever/Connect-4/assets/69628500/3054f774-9c65-4bde-8563-e85b1b34ec34)

**Comment by withrvr** [comment]
# comman check box
- to allow the same ... name/color/image
- else not allowed

**Comment by VaishnavGhenge** [comment]
Feature implemented!
